### ISSUE TITLE
Allocating Agent Namespace requirement

### ISSUE THREAD

**Issue by xgmachina** [IGSN/igsn.github.io#1]
Dear there,

We are an IGSN full member and want to set up an IGSN allocating agent at RPI. Could we apply two namespaces:

10273/DCO
10273/RPI

Thanks,

Xiaogang (Marshall) Ma

Associate Research Scientist in Semantic eScience
Tetherless World Constellation
Rensselaer Polytechnic Institute
110 8th Street, Troy, NY 12180, USA
E-mail: max7@rpi.edu
Homepage: http://homepages.rpi.edu/~max7

**Comment by jklump** [comment]
Request sent to members for comment.

**Comment by HJWallrabe** [comment]
Hi,
it's fine for us.

Dr. Hans-Joachim Wallrabe-Adams

Project Data Management
University of Bremen, MARUM
PANGAEA Data Library
ECORD Science Operator Data Management
Hochschulring 18
D-28359 Bremen
Germany
Phone: +49 (0)421 218 65592
hwallrabe@uni-bremen.de
hjwallrabeadams@marum.de

**Comment by mcorlando** [comment]
Request from RPI for namespaces 10273/DCO and 10273/RPI has been approved. Marshall has been notified via email.

**Comment by jklump** [comment]
Namespace allocated.
