### ISSUE TITLE
Namespace request: CNRSXXXXXXXXXX

### ISSUE THREAD

**Issue by jescartin** [IGSN/igsn.github.io#11]
Hello,

To set up the French rock repository at IPGP, we request a namespace to assign IGSN numbers to the samples, with the prefix CNRS, followed by 10 numbers; e.g.: CNRSXXXXXXXXXX.

CNRS has not been set up yet as an allocating agency.   In the meantime, this namespace will be associated to the account escartin.javier@gmail.com. In the meantime IEDA will act as allocating agency.

Best regards,

Javier Escartin

**Comment by mcorlando** [comment]
The request for CNRS has been approved.

We discussed among the ExTeam whether it is likely that the Chinese Geological Survey will become and allocating agent. Should the Chinese join, they could still request a namespace that begins with CNX, where X is any number or letter that is not R.

Damien, please allocate the code to IEDA.
