### ISSUE TITLE
Namespace request: AW

### ISSUE THREAD

**Issue by ulbricht** [IGSN/igsn.github.io#19]
Hi,

GFZ is applying for namespace "AW". The namespace will be used to mint IGSN for Alfred Wegener Institute.

'Registered IGSN Namespaces' has been checked (http://igsn.github.io/registered/) and the namespace "AW" is not currently registered.

Best regards
Damian

**Comment by jklump** [comment]
I see no problems with this namespace being assigned to GFZ for AWI.

Best regards
Jens

**Comment by jklump** [comment]
resolved
