### ISSUE TITLE
Namespace request: AG

### ISSUE THREAD

**Issue by Geofab76** [IGSN/igsn.github.io#20]
Hi,

Lithodat is applying for namespace "AG". The namespace will be used for minting IGSNs for the Australian Geochemistry Laboratory Network: AusGeochem. The allocating agent will be Lithodat Pty Ltd.

We already checked the registered namespaces on http://igsn.github.io/registered/ and the namespace "AG" is still free.

Kind regards,

Fabian

**Comment by jklump** [comment]
issue closed
