### ISSUE TITLE
Namespace request: LD

### ISSUE THREAD

**Issue by Geofab76** [IGSN/igsn.github.io#21]
Hi,

Lithodat is applying for the namespace "LD". The namespace will be used for minting IGSNs via Lithodat's LithoSurfer community platform, which will enable our clients, academic communities and public users to mint and register their samples. The allocating agent will be Lithodat Pty Ltd.

We already checked the registered namespaces on http://igsn.github.io/registered/ and the namespace "LD" is still free.

Kind regards,

Fabian

**Comment by jklump** [comment]
Issue closed
