### ISSUE TITLE
Namespace MCA for McArthur Basin Project

### ISSUE THREAD

**Issue by jklump** [IGSN/igsn.github.io#3]
The McArthur Basin Project is a joint project of CSIRO and the Northern Territory Geological Survey (NTGS). The project is asking to use the namespace MCA, which is not taken at moment.

**Comment by jklump** [comment]
CSIRO - OK

**Comment by brent-jdlc** [comment]
This is a fundamental issue for IGSN. Are namespaces to be used solely for institutions or both institutions and projects? My view is that namespaces should be dedicated to institutions.

**Comment by jklump** [comment]
Most current namespaces are for projects, which is a legacy issue going back to how SESAR used to operate. To avoid namespace exhaustion we moved away from giving namespaces to small projects. The McArthur Basin Project is expeting on the order of 100,000 samples and it is a joint project between two institutions. I think, in this case a separate namespace would be justified.

**Comment by jklump** [comment]
GA is in colsultation with the geological surveys of the Australian states and territories.

**Comment by jklump** [comment]
The matter was discussed at a technical meeting in Denver, CO, today. Our recommendation is to use a subnamespace, either in the namespace of CSIRO or of GA. Example: CSMACxxxxx or AUMACxxxxx.

**Comment by brent-jdlc** [comment]
Thanks for sharing. I believe that this is an appropriate decision and will permit a more structured approach to IGSN implementation.

Regards

Brent

Sent from my iPad

On 15 Sep 2016, at 01:20, Jens Klump <notifications@github.com<mailto:notifications@github.com>> wrote:

The matter was discussed at a technical meeting in Denver, CO, today. Our recommendation is to use a subnamespace, either in the namespace of CSIRO or of GA. Example: CSMACxxxxx or AUMACxxxxx.

##

**Comment by jklump** [comment]
Namespace request declined on basis of discussion documented above and in http://igsn.github.io/2016/09/14/Denver-technical-meeting/.
