### ISSUE TITLE
Multiple namespaces for GA

### ISSUE THREAD

**Issue by jklump** [IGSN/igsn.github.io#4]
GA is applying for the use of several namespaces on behalf of the geological surveys of the Australian states and territories.

WA
NT
QLD
VIC
SA
NSW
ACT
TAS

The namespaces are not assigned. http://igsn.github.io/registered/

The consultation period ends on 2016-09-30.

**Comment by mcorlando** [comment]
As you can see from the list of registered namespaces at http://igsn.github.io/registered/, SAB is currently in use at IEDA. This could potentially conflict with the namespace SA.

We do not have any other objections.

**Comment by jklump** [comment]
Thank you all for your response to the GA request for name spaces.

I would like to suggest an open discussion regarding this request. Some members have serious concerns about the request relating to the limited number of 2-digit name spaces that the IGSN e.V. has available and the speed with which we will be using up these name spaces if we do not have clear criteria that make organizations eligible for a 2-digit name space. I think we should hold off 'votes' until we have had the opportunity to discuss the implications of our decision regarding the GA request.

A small group from the IGSN e.V. including members of the ExCom is meeting here in Denver at the International Data Week, and I hope we can agree on a path forward.

**Comment by jklump** [comment]
The conclusion of today's discussion was to recommend against the proposed namespaces. The idea of high-level namespaces was to make best use of the available namespace by creating subnamespaces. Geoscience Australia already governs the namespace AU which could be extended by state and territory abbreviations. Examples: AUTASxxxxx, AUWAxxxxxx, AUQLDxxxxx

**Comment by nicholascar** [comment]
AU + state code (AUACT, AUNSW...) seem sensible to me!

**Comment by jklump** [comment]
Namespace request declined based on discussion outlined above and in http://igsn.github.io/2016/09/14/Denver-technical-meeting/.
