### ISSUE TITLE
Namespace request by IFREMER

### ISSUE THREAD

**Issue by vtosello** [IGSN/igsn.github.io#8]
Hello,
I am applying for the use of FRB namespace for IFREMER repository. If not possible, BFR could be another option.
Thanks in advance
Best regards
Vanessa

**Comment by jklump** [comment]
Hi Vanessa,
As discussed at the workshop in New Orleans, I would want to reserve the namespace FR* for BRGM. The namespace BF* is not claimed by anyone yet (see http://igsn.github.io/registered/). The ISO 3166-2 Country Code BF stands for Burkina Faso https://en.wikipedia.org/wiki/ISO_3166-2:BF. The Executive Board will discuss whether this is an issue.

**Comment by jklump** [comment]
No objections from the Executive Board. Namespace BF* approved for use by IFREMER.

**Comment by jklump** [comment]
Assign namespace BF to IFREMER.

**Comment by ulbricht** [comment]
Hi Jens and Vanessa,
added it on the info page (http://igsn.github.io/registered/). To setup an account for minting here https://doidb.wdc-terra.org/igsn I need an email contact.

**Comment by vtosello** [comment]
Hi,
Best wishes for 2018!
You can use my email address: vanessa.tosello@ifremer.fr, unless it's better to use a generic e-mail address?
Best regards
Vanessa

**Comment by ulbricht** [comment]
Account created.
