### ISSUE TITLE
Applying for a namespace

### ISSUE THREAD

**Issue by GerryRyder** [IGSN/igsn.github.io#9]
Hello

We are an IGSN full member and wish to become an allocating agent.  

We are applying for the namespace 22.  

We understand that a 2 digit alpha code is commonly requested, however, as with our DOI minting service, we wish to adhere to a policy of assigning only non-meaningful opaque identifiers.  Our DOI service policy references section 2.2 of the DataCite handbook in this matter.

Please advise if any further information is required. Thank you for your consideration.

Gerry Ryder
Research Data Management Specialist | Australian National Data Service
T: +61 8 83038687 | E:  gerry.ryder@ands.org.au| W: ands.org.au 
Physical address: CSIRO Waite Campus, Waite Rd, Urrbrae, SA, Australia, 5064
Postal address: c/- CSIRO, PMB 2, Glen Osmond, SA, Australia, 5064

**Comment by jklump** [comment]
Hi Gerry,

I understand the reasoning behind your request, but unfortunately it does not conform with our syntax recommendations http://igsn.github.io/syntax/. We need to discuss this further or find alternatives.

My ad-hoc recommendation for ANDS would be the namespace AX.

Regards

Jens

**Comment by GerryRyder** [comment]
Thank you Jens.  Following discussion with Adrian, can we propose instead XX?  Easy to remember and one of the least linguistic options.

Thanks,  Gerry

**Comment by jklump** [comment]
Namespace granted to ANDS by the IGSN Executive Board.
